### ISSUE TITLE
vmp stuck in in-progress state when applying an ANP with no rules

### ISSUE THREAD

**Issue by shenmo3** [antrea-io/nephe#129]
**Describe the bug**
When applying an ANP with no rules and some appliedTo resources, the vmp will stuck in `in-progress` state.

**To Reproduce**
1. Import some cloud VMs
2. Apply following example ANP
```yaml
apiVersion: crd.antrea.io/v1alpha1
kind: NetworkPolicy
metadata:
  name: vm-anp
  namespace: sample-ns
spec:
  priority: 1
  appliedTo:
  - externalEntitySelector:
      matchLabels:
         kind.nephe: virtualmachine
```

**Expected**
`kubectl get anp -A` showing desired node 1 and current node 1.
`kubectl get vmp -A` showing all three VM and all `SUCCESS`.
All Cloud VM has empty SG attached.

**Actual behavior**
`kubectl get vmp -A` showing all three VM stuck in `IN-PROGRESS`.
Other two behaviors are correct. 

**Versions:**

**Additional context**
This bug is likely caused by function at `pkg/controllers/cloud/networkpolicy.go` L1578, `getStatus()`.
In `networkpolicy_cloudresource.go` L236, nephe uses `np.getStatus()` to check if np is ready or still in progress. The `getStatus` function will return in progress state if there are no internal np rules ready, thinking that np is still processing and computing rules. However, in the case that there are no rules in the first place, this will never return a ready state.
