### ISSUE TITLE
Do not expand IPBlock or ASG for Azure rule

### ISSUE THREAD

**Issue by reachjainrahul** [antrea-io/nephe#299]
**Describe the problem/challenge you have**

If an Antrea NetworkPolicy contains IPBlock or AddressGroup, each of the entry is translated to separate rule in Azure NSG. This will have scale implication as Azure NSG can support only 1000 rules.

**Describe the solution you'd like**

Add compression login in Azure plugin to combine IPBlock and Address groups of ANP in 1 rule.

**Comment by reachjainrahul** [comment]
Further, if a rule contains more than 1 services (port), for each port, a unique rule will be created in Azure cloud. This is not optimal.

For example,
```
apiVersion: crd.antrea.io/v1alpha1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: azure-ns
spec:
  priority: 10
  appliedTo:
  - group: all-vms
  ingress:
  - from:
      - ipBlock:
          cidr: 1.1.0.0/24
    action: Drop
    ports:
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 80
```

This will translate to two rules.
